spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: MOVIEDB
    password: 14292
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl