security:
  jwt:
    key-store: classpath:authorize.jks
    key-store-password: 14292Auth
    key-pair-alias: authorize
    key-pair-password: 14292Auth

spring:
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
    username: SECURITYDB
    password: 14292
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate